moving to GitHub Actions
adafruit/Adafruit_FXOS8700 pull request #5
Opened 2020-01-13 23:50 UTC by siddacious

2020-01-13 23:52 UTC, ladyada approved these changes

2020-01-14 00:47 UTC, ladyada requested changes

2020-01-14 00:47 UTC, ladyada commented on .github/workflows/githubci.yml
> +        PRETTYNAME : "Adafruit FXOS8700 Accelerometer/Magnetometer Library"
remove /

2020-01-14 03:51 UTC, hathach commented on .github/workflows/githubci.yml
> +on: [pull_request, push]
please add `repository_dispatch` to the event list as well, it should be 
```
on: [pull_request, push, repository_dispatch]
```

2020-01-15 03:27 UTC, merged